name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Klemensas/action-autotag@1.2.3
      with:
        GITHUB_TOKEN: "${{ secrets.AUTO_TAG }}"
